version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: eventweb-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eventweb-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eventweb-frontend
    restart: always
    ports:
      - "3000:80"  # Access frontend at localhost:3000
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

volumes:
  mongodb_data:
