version: "3.8"

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "${PORT_BACKEND}:${PORT_BACKEND}"
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - FRONTEND_URL=http://frontend:${PORT_FRONTEND}

  frontend:
    build:
      context: ./frontend
    ports:
      - "${PORT_FRONTEND}:${PORT_FRONTEND}"
    env_file:
      - .env
    depends_on:
      - backend
