name: my first setup

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        cd frontend
        npm ci
    - run: |
        cd backend
        npm ci
    - run: |
        cd frontend
        npm install
    - run: |
        cd backend
        npm install
    - run: |
        cd frontend
        npm run build --if-present
    - run: |
        cd frontend
        npm test
    - run: |
        cd backend
        npm test